/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kushetka

import java.net.URL
import kotlin.test.Test
import kotlin.test.assertTrue

class KushetkaTest {
    @Test
    fun constructDatabaseAndInsert() {
        val couchDbServer = Kushetka.getServer("http://localhost:5984")
        val catsDb = couchDbServer.getDb("cats")

        data class Cat(
            val name: String,
            val lazinessScore: Int,
            val maliciousDisposition: Boolean = true
        )

        listOf(
            Cat("lucy", 45, true),
            Cat("mittens", 87, true),
            Cat("george", 52, false)
        ).forEach { cat ->
            catsDb.insert(cat, cat.name)
        }

        val mittens = catsDb.findById<Cat>("mittens") ?: error("mittens could not be found")

        assertTrue(mittens.lazinessScore == 87)
    }
}
