/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kushetka

import kushetka.CouchDbServer.Credentials
import java.net.URL

object Kushetka {
    fun getServer(baseUrl: String, credentials: Credentials? = null): CouchDbServer {
        return getServer(URL(baseUrl), credentials)
    }
    fun getServer(baseUrl: URL, credentials: Credentials? = null): CouchDbServer {
        return CouchDbServer(baseUrl, credentials)
    }
}
